In [1]:
import pandas as pd
import numpy as np

In [2]:
# Возьмем классический датасет про ирисы (у нас 4 признака в х, а в таргете оставим только 0 и 1 вид). 

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = pd.DataFrame(iris.target)

In [6]:
df = df.loc[df.species < 2]

In [7]:
df.species.value_counts()

1    50
0    50
Name: species, dtype: int64

In [8]:
df.shape

(100, 5)

In [9]:
df = df.sample(frac=1) 

In [10]:
y = df.species

In [11]:
x = df.drop('species', axis=1)

In [12]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
85                6.0               3.4                4.5               1.6
42                4.4               3.2                1.3               0.2
65                6.7               3.1                4.4               1.4
1                 4.9               3.0                1.4               0.2
27                5.2               3.5                1.5               0.2

In [13]:
y.head()

85    1
42    0
65    1
1     0
27    0
Name: species, dtype: int64

In [14]:
# размер данных

m, n = np.shape(x)
m, n

(100, 4)

In [15]:
# преобразуем x к следующему виду
x = np.c_[ np.ones(m), x]
x[:5]

array([[1. , 6. , 3.4, 4.5, 1.6],
       [1. , 4.4, 3.2, 1.3, 0.2],
       [1. , 6.7, 3.1, 4.4, 1.4],
       [1. , 4.9, 3. , 1.4, 0.2],
       [1. , 5.2, 3.5, 1.5, 0.2]])

In [16]:
# y лист значений
y[:5]

85    1
42    0
65    1
1     0
27    0
Name: species, dtype: int64

In [17]:
# Ручной алгоритм LogisticRegression

In [18]:
# шаг алгоритма
alpha = 0.01

In [19]:
def gradient_descent_logisticregression(alpha, x, y, numIterations):
    """
    Функция реализует алгоритм градиентного спуска. На каждом шаге выводится значение функции потерь
    """
    
    m = x.shape[0] # 100
    theta = np.ones(5) # произвольно задаем начальные коэффициенты
    x_transpose = x.transpose() # транспонированная матрица x
    
    for iter in range( 0, numIterations ):
        matr = x@theta # матричное произведение
        
        hypothesis = 1/(1+np.exp(-matr)) # наш прогнозный таргет
        
        logloss = -y*np.log(hypothesis) - (1-y)*np.log(1-hypothesis)      
        
        J = np.sum(logloss)/(m) 

        print("J : ", J)
        
        gradient = (hypothesis-y)@x     
        
        theta = theta - alpha * gradient  
    
    return theta

In [20]:
def predict_y(x,theta):
    matr = x@theta
    hypothesis = 1/(1+np.exp(-matr))
    return hypothesis

In [21]:
%%time
theta = gradient_descent_logisticregression(alpha, x, y, 2000)

J :  5.57101003508983
J :  4.04543456308919
J :  7.254213582791238
J :  0.27806381525352414
J :  1.9463925357630905
J :  4.842128124224181
J :  3.852634067585271
J :  0.772950014598791
J :  2.2366683470237887
J :  0.8717408440254271
J :  1.0704290419309372
J :  0.0857862881890558
J :  0.0037270679618491916
J :  0.003138908615552427
J :  0.0027165074023953674
J :  0.002398064462394427
J :  0.0021492816900198315
J :  0.0019495311008136246
J :  0.001785634897540457
J :  0.0016487685200930198
J :  0.0015327942469838846
J :  0.001433307809348573
J :  0.0013470650408576176
J :  0.0012716224907036674
J :  0.0012051041276607266
J :  0.0011460452841899104
J :  0.0010932855166082668
J :  0.0010458933530859912
J :  0.0010031123637647289
J :  0.0009643218124565571
J :  0.0009290074823706507
J :  0.0008967397296281009
J :  0.0008671567557313594
J :  0.000839951704541486
J :  0.0008148625998988548
J :  0.0007916644193106581
J :  0.0007701627922061324
J :  0.0007501889467365565
J :  0.000731595625468

J :  0.0003511620437955751
J :  0.0003510557305802589
J :  0.00035094949645115056
J :  0.00035084334098914343
J :  0.000350737263785555
J :  0.0003506312644419314
J :  0.0003505253425696795
J :  0.0003504194977898214
J :  0.0003503137297326608
J :  0.00035020803803754454
J :  0.00035010242235257964
J :  0.00034999688233441136
J :  0.00034989141764793513
J :  0.00034978602796602814
J :  0.0003496807129694171
J :  0.0003495754723463436
J :  0.00034947030579240935
J :  0.0003493652130103353
J :  0.0003492601937097319
J :  0.0003491552476069398
J :  0.0003490503744248307
J :  0.0003489455738925565
J :  0.0003488408457454923
J :  0.00034873618972487805
J :  0.000348631605577822
J :  0.00034852709305702943
J :  0.0003484226519206291
J :  0.0003483182819321067
J :  0.000348213982860051
J :  0.00034810975447808074
J :  0.0003480055965646437
J :  0.0003479015089029044
J :  0.0003477974912805989
J :  0.0003476935434899282
J :  0.00034758966532738816
J :  0.00034748585659365785
J :  0.00034738211

J :  0.0003159660419883762
J :  0.00031588115216960825
J :  0.0003157963100779134
J :  0.00031571151567233056
J :  0.00031562676891200937
J :  0.000315542069756095
J :  0.0003154574181638272
J :  0.00031537281409445186
J :  0.0003152882575073105
J :  0.0003152037483617412
J :  0.0003151192866171597
J :  0.0003150348722329878
J :  0.00031495050516879003
J :  0.0003148661853840645
J :  0.00031478191283842077
J :  0.0003146976874914967
J :  0.0003146135093029934
J :  0.00031452937823260834
J :  0.0003144452942401622
J :  0.00031436125728546857
J :  0.00031427726732840097
J :  0.0003141933243288558
J :  0.00031410942824683033
J :  0.00031402557904231594
J :  0.00031394177667537824
J :  0.00031385802110611477
J :  0.00031377431229469586
J :  0.0003136906502012794
J :  0.0003136070347861331
J :  0.00031352346600950975
J :  0.00031343994383178925
J :  0.0003133564682133084
J :  0.0003132730391145175
J :  0.00031318965649587346
J :  0.0003131063203178849
J :  0.00031302303054109347
J :  0.0003

J :  0.0002882037328823901
J :  0.0002881337026843515
J :  0.00028806370807617253
J :  0.00028799374903032236
J :  0.0002879238255192072
J :  0.00028785393751534164
J :  0.00028778408499123114
J :  0.0002877142679194195
J :  0.00028764448627244325
J :  0.0002875747400229366
J :  0.0002875050291435196
J :  0.00028743535360682546
J :  0.0002873657133855543
J :  0.00028729610845240855
J :  0.00028722653878011847
J :  0.0002871570043414756
J :  0.00028708750510925596
J :  0.0002870180410562824
J :  0.0002869486121554255
J :  0.0002868792183795316
J :  0.00028680985970153274
J :  0.00028674053609437094
J :  0.00028667124753100503
J :  0.0002866019939844006
J :  0.000286532775427611
J :  0.00028646359183367656
J :  0.00028639444317566314
J :  0.0002863253294266711
J :  0.000286256250559862
J :  0.00028618720654837197
J :  0.0002861181973653852
J :  0.00028604922298413883
J :  0.00028598028337783175
J :  0.00028591137851977034
J :  0.0002858425083832566
J :  0.0002857736729415899
J :  0.00028

J :  0.0002645113315081931
J :  0.00026445280178523573
J :  0.000264394299135469
J :  0.00026433582353977504
J :  0.0002642773749791031
J :  0.00026421895343438687
J :  0.000264160558886602
J :  0.0002641021913167189
J :  0.0002640438507057503
J :  0.0002639855370347044
J :  0.00026392725028463835
J :  0.00026386899043655607
J :  0.0002638107574716036
J :  0.0002637525513707853
J :  0.00026369437211528723
J :  0.00026363621968618903
J :  0.00026357809406465265
J :  0.0002635199952318158
J :  0.00026346192316889917
J :  0.00026340387785706514
J :  0.00026334585927753016
J :  0.0002632878674115409
J :  0.0002632299022403606
J :  0.0002631719637452308
J :  0.00026311405190744465
J :  0.0002630561667083047
J :  0.00026299830812913356
J :  0.0002629404761512768
J :  0.00026288267075608607
J :  0.00026282489192490615
J :  0.00026276713963917296
J :  0.0002627094138802661
J :  0.000262651714629634
J :  0.00026259404186870577
J :  0.0002625363955789422
J :  0.00026247877574181536
J :  0.000262

J :  0.0002449546114900635
J :  0.00024490476303996276
J :  0.00024485493578530143
J :  0.000244805129712383
J :  0.0002447553448074586
J :  0.0002447055810568215
J :  0.00024465583844675986
J :  0.00024460611696359573
J :  0.0002445564165936594
J :  0.00024450673732325336
J :  0.00024445707913875664
J :  0.00024440744202652517
J :  0.0002443578259729202
J :  0.0002443082309643211
J :  0.0002442586569871248
J :  0.000244209104027734
J :  0.0002441595720725902
J :  0.00024411006110807942
J :  0.00024406057112067768
J :  0.0002440111020968145
J :  0.000243961654022977
J :  0.00024391222688563473
J :  0.0002438628206712616
J :  0.00024381343536637284
J :  0.00024376407095747462
J :  0.00024371472743110092
J :  0.00024366540477376041
J :  0.0002436161029720349
J :  0.00024356682201245522
J :  0.0002435175618815878
J :  0.00024346832256604022
J :  0.0002434191040523901
J :  0.0002433699063272539
J :  0.00024332072937722915
J :  0.00024327157318895822
J :  0.000243222437749062
J :  0.0002431

In [22]:
print(theta)

[ 0.11849118 -1.39134581 -3.46004014  5.7593335   3.1665473 ]


In [23]:
y_hat = predict_y(x, np.array(theta))

In [24]:
def get_labels(y_hat, treshhold=0.5):
    y_corr = []
    for i in y_hat:
        if i >= treshhold:
            y_corr.append(1)
        else:
            y_corr.append(0)
    return y_corr

In [25]:
y_corr = get_labels(y_hat)

In [26]:
for i in zip(y_corr, y):
    print(i)

(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)


In [27]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_corr,y))

1.0


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_corr,y))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [29]:
# LogisticRegression "из коробки"

In [30]:
from sklearn.linear_model import LogisticRegression

In [31]:
lr = LogisticRegression()

In [32]:
x.shape

(100, 5)

In [33]:
lr.fit(x, y)

/home/lena/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
lr.coef_

array([[-0.24858192, -0.37024431, -1.4418742 ,  2.23801444,  0.99761008]])

In [35]:
lr.intercept_

array([-0.24858192])

In [36]:
y_hat = lr.predict(x)

In [37]:
print(classification_report(y,y_hat))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        50

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [38]:
for i in zip(y_hat, y):
    print(i)

(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
