In [1]:
3*0.25**2+0.75**2

0.75

In [2]:
sqrt(0.75)

NameError: name 'sqrt' is not defined

In [3]:
import numpy as np

In [14]:
Anorm = np.sqrt(0.75)

In [34]:
Anorm

0.8660254037844386

In [5]:
a = 11.25**2+48.75**2+16.25**2+21.25**2

In [15]:
Bnorm = np.sqrt(a)

In [8]:
A = np.array([-0.25, 0.75, -0.25, -0.25])

In [12]:
A

array([-0.25,  0.75, -0.25, -0.25])

In [13]:
B = np.array([-11.25, 48.75, -16.25, -21.25])

In [18]:
AA = A/Anorm

In [60]:
AA

array([-0.28867513,  0.8660254 , -0.28867513, -0.28867513])

In [61]:
Ast

array([-0.28867513,  0.8660254 , -0.28867513, -0.28867513])

In [19]:
BB = B/Bnorm

In [62]:
BB

array([-0.19829369,  0.85927267, -0.28642422, -0.37455475])

In [63]:
Bst

array([-0.19829369,  0.85927267, -0.28642422, -0.37455475])

In [20]:
(AA+BB)/np.sqrt(2)

array([-0.34433896,  1.21996996, -0.40665665, -0.46897435])

In [21]:
A = np.array([1,2,1,1])
B = np.array([70,130,65,60])

In [23]:
Am = A.mean()

In [30]:
Acentr = A - Am

In [31]:
Bm = B.mean()

In [32]:
Bcentr = B - Bm

In [36]:
Ast = Acentr/np.linalg.norm(Acentr)

In [35]:
Bst = Bcentr/np.linalg.norm(Bcentr)

In [38]:
Mcorr = np.array([[1, 0.9922], [0.9922, 1]])

In [42]:
Mcorr

array([[1.    , 0.9922],
       [0.9922, 1.    ]])

In [39]:
np.linalg.eig(Mcorr)

(array([1.9922, 0.0078]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [41]:
1 - 1.9922

-0.9922

In [44]:
x = np.array([-0.9922, 0.9922])
y = np.array([1,1])

In [45]:
x@y.T

0.0

In [48]:
y = np.array([0.70710678, 0.70710678])

In [49]:
x@y.T

0.0

In [64]:
gl = (Ast + Bst)/np.linalg.norm(Ast + Bst)

In [65]:
gl

array([-0.24396044,  0.86433557, -0.28811186, -0.33226327])

In [59]:
y

array([0.70710678, 0.70710678])