In [1]:
import numpy as np

Husband_Income=np.array([100,220,140])
Wife_Income=np.array([150,200,130])
Lover_Income=np.array([90,80,100])

Husband_Сonsumption=np.array([50,50,60])
Wife_Сonsumption=np.array([100,80,140])
Lover_Сonsumption=np.array([100,20,140])

In [4]:
# 1
Inc = np.array([Husband_Income, Wife_Income, Lover_Income])

In [5]:
Inc.T

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [7]:
np.vstack([Husband_Income, Wife_Income, Lover_Income])

array([[100, 220, 140],
       [150, 200, 130],
       [ 90,  80, 100]])

In [8]:
np.hstack([Husband_Income, Wife_Income, Lover_Income])

array([100, 220, 140, 150, 200, 130,  90,  80, 100])

In [11]:
np.dstack([Husband_Income, Wife_Income, Lover_Income])

array([[[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]]])

In [12]:
# 2
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Lover_Сonsumption])
Cons.T

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [14]:
# 3
Inc.T*0.87

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [19]:
# 4
Inc.T*0.87-Cons.T

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])