In [2]:
import numpy as np

In [3]:
a = np.array([3, 4, 5, 9])
b = np.array([1, 5, 3, 6])

In [6]:
c = - 200*a + 400*b

In [7]:
print(c)

[-200 1200  200  600]


In [8]:
import math

In [9]:
np.sqrt(53)

7.280109889280518

In [3]:
import pandas as pd

In [4]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [5]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [6]:
Hut_Paradise_DF.loc[4,:]

1.Rent              40
2.Area              33
3.Rooms              1
4.Floor              6
5.Demo two weeks    20
6.Liv.Area          16
Name: 4, dtype: int64

In [10]:
# 1
ht = Hut_Paradise_DF.values
print(ht[4])

[40 33  1  6 20 16]


In [11]:
# 2
print(ht[:, 3])

[ 5 12 10  3  6 13  8 21  5]


In [13]:
# 3
print(ht[2, 3])

10


In [14]:
# 4
len(ht)

9

In [16]:
# 5
ht[:,1]-ht[:,5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

In [20]:
# 6
grivny = ht[:,0]*0.4

In [23]:
np.array(grivny, dtype = 'int')

array([26, 28, 48, 14, 16, 20, 40, 36, 34])

In [25]:
# 7
minutes = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [26]:
minutes@ht[:,4]

1348

In [27]:
np.dot(minutes, ht[:,4])

1348

In [28]:
# 2

In [29]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [30]:
print(np.dot(u,v))
print(np.dot(v, w))
print(np.dot(u,w))

0
0
0


In [31]:
# 8
2*v-3*w

array([-3, 14,  3,  4,  2])

In [32]:
# 9
a = 2*v-3*w
np.dot(u, a)

0

In [37]:
# 10
u_norm = u/np.linalg.norm(u)
print(u_norm)

[0.8660254  0.         0.28867513 0.28867513 0.28867513]


In [38]:
v_norm = v/np.linalg.norm(v)
print(v_norm)

[ 0.          0.33333333  0.          0.66666667 -0.66666667]


In [39]:
w_norm = w/np.linalg.norm(w)
print(w_norm)

[ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]


In [40]:
np.linalg.norm(u_norm)

1.0